### ISSUE TITLE
postgres

### ISSUE THREAD

**Issue by mr-eaze** [mr-eaze/avocado_plus#2]
![screenshot 2015-05-07 15 57 01](https://cloud.githubusercontent.com/assets/5388357/7525114/df389200-f4d4-11e4-8714-6416bd030bfe.png)
![screenshot 2015-05-07 16 12 37](https://cloud.githubusercontent.com/assets/5388357/7525115/df3aead2-f4d4-11e4-83a6-731ab3c8514b.png)

**Comment by mr-eaze** [comment]
Hi sorry, my issue is not fully developed yet... but short story is that this has been a recurring issue for me, and I'm not sure how to fix it... it seems to be the result of a "quick-fix" Tony helped me with in class one day when my Postgresql server wasn't working, but now I'm feeling at the mercy of the Postgres App?

**Comment by mr-eaze** [comment]
Note: this is not related to my app/project specifically... but it's preventing me from moving forward with my project because I can't "trust" my database to be consistent/reliable.

**Comment by mr-eaze** [comment]
Update: I have un-installed the Postgres App locally... if the issue/error message shows up again I will holla-atcha-boi!

**Comment by bigtone1284** [comment]
@DrRobotmck Hi McK
